---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: httpd-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce

  nfs:
    server: 172.31.39.58
    path: "/home/ec2-user/test/"


#this PersistentVolumeclaim yml file
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce


# refering claim in pod yum file
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-rs
  template:
    metadata:
      name: httpd-pod
      labels:
        app: httpd-rs
    spec:
      containers:
        - image: httpd
          name: httpd-cotainer
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: "/usr/local/apache2/htdocs/"
            name: httpd-volume
      volumes:
      - name: httpd-volume
        persistentVolumeClaim:
          claimName: httpd-pvc
#this service for jenkins replicaset
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  labels:
    app: httpd-svc
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: httpd-rs
