---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: httpd-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce

  nfs:
    server: 172.31.39.58
    path: "/home/ec2-user/test/"


#this PersistentVolumeclaim yml file
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce


# refering claim in pod yum file
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
  - name: httpd-container
    image: httpd
    volumeMounts:
    - mountPath: /test-pd
      name: httpd-volume
  volumes:
  - name: httpd-volume
    persistentVolumeClaim:
      claimName: httpd-pvc
