apiVersion: v1
kind: Service
metadata:
        name: nginx
        labels:
          app: my-nginx
spec:
        type: NodePort
        ports:
                - port: 80
                  nodePort: 30002
                  protocol: TCP
        selector:
                app: my-nginx

