apiVersion: v1
kind: Service
metadata:
        name: tomcat
        labels:
          app: my-tomcat
spec:
        type: NodePort
        ports:
                - port: 80
                  nodePort: 30008
                  protocol: TCP
        selector:
                app: my-tomcat

