apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  selector:
     app: my-nginx
  template:
    metadata:
       labels:
         app: my-nginx
    spec:
      containers:
      - image: nginx
        name: my-nginx
        ports:
          - containerPort: 8080

