apiVersion: v1
kind: ReplicationController
metadata:
        name: my-tomcat
spec:
        replicas: 3
        selector:
                app: my-tomcat
        template:
                metadata:
                        labels:
                                app: my-tomcat
                spec:
                        containers:
                        - image: tomcat
                          name: my-tomcat
                          ports:
                                  - containerPort: 8080
